//
//  DataModel.swift
//  Death's Diary
//
//  Created by Greg Durrett on 5/9/18.
//  Copyright © 2018 AppHazard Productions. All rights reserved.
//

import Foundation
import UIKit

class DataModel {
    
    static var sharedInstance = DataModel()
    
    var allHuntEvents = [HuntEvent]()
    var allEventResults = [EventResult]()
    
    private init() {
        
        let eventResult1a = EventResult(eventDieResult: "1 - 5", eventResultDescription: NSMutableAttributedString().appendWith("You fumble and cut your foot on a jagged shard. Suffer monster level event damage to your legs."))
        let eventResult1b = EventResult(eventDieResult: "6 - 8", eventResultDescription: NSMutableAttributedString().appendWith("You salvage something useful. Gain 1 ").appendWith(weight: .bold, "broken lantern").appendWith(" basic resource."))
        let eventResult1c = EventResult(eventDieResult: "9+", eventResultDescription: NSMutableAttributedString().appendWith("The survivors uncover a long-abandoned lantern hoard. The forlorn sight fills them with dread: each survivor sets their insanity to 0. After composing themselves, each survivor scavenges 1").appendWith(weight: .bold, " broken lantern").appendWith(" basic resource; add them to settlement storage."))
        let huntEvent1 = HuntEvent(eventNumber: "0", eventText: NSMutableAttributedString().appendWith("The survivors feel something crunching beneath their feet. The event revealer may choose to lower their lantern and ").appendWith(weight: .bold, "investigate").appendWith(" or ignore the sensation and continue their journey.\n\nIf they choose to investigate, the event revealer gains +1 courage and rolls 1d10. Otherwise, roll again on the hunt event table before moving on the hunt event board."), eventTitle: "1 | Broken Lanterns", eventDie: "1d10", eventDieRoller1: "Event Revealer - Investigate", eventResults1: [eventResult1a, eventResult1b, eventResult1c])
        allHuntEvents.append(huntEvent1)
        
        let huntEvent2 = HuntEvent(eventNumber: "1", eventText: NSMutableAttributedString().appendWith("The survivors are overcome by a sudden chill, their breath seizing in their lungs. The survivors' teeth chatter mercilessly. All survivors lose monster level survival. At the center of the sudden frost is a perfectly-preserved corpse.\n\nIf the settlement has ").appendWith(weight: .bold, "Cannibalize").appendWith(", the event revealer gains 1 random basic resource.\n\nIf the settlement has ").appendWith(weight: .bold, "Graves").appendWith(", the event revealer examines the corpse and gains +1 courage and +1 understanding.\n\nIf the settlement has ").appendWith(weight: .bold, "Memento Mori").appendWith(", the event revealer uderstands a little about what happened to the corpse. They gain 1 random fighting art."), eventTitle: "2 | Corpse", eventDie: "N/A", eventDieRoller1: "Event Revealer", eventResults1: [])
        allHuntEvents.append(huntEvent2)

        let eventResult3a = EventResult(eventDieResult: "1 - 3", eventResultDescription: NSMutableAttributedString().appendWith("Running and flailing wildly, you suddenly find yourself panicked and alone. The waiting cancer pigeons descend and mercilessly peck your back, their happy cooing filling your head with horror. An hour later, the other survivors find you balled up and weeping on the ground. You are ").appendWith(weight: .bold, "Dead Inside").appendWith(": you cannot gain survival. Record this impairment."))
        let eventResult3b = EventResult(eventDieResult: "4 - 6", eventResultDescription: NSMutableAttributedString().appendWith("A cancer pigeon latched onto your back!, Shake it free by spending 1 survival. Otherwise, you are ").appendWith(weight: .bold, "Dead Inside").appendWith(": you cannot gain survival. Record this impairment."))
        let eventResult3c = EventResult(eventDieResult: "7 - 8", eventResultDescription: NSMutableAttributedString().appendWith("You escape the terrible creatures."))
        let eventResult3d = EventResult(eventDieResult: "9+", eventResultDescription: NSMutableAttributedString().appendWith("You manage to strike one of the foul creatures down. Gain 1 random basic resource."))
        let huntEvent3 = HuntEvent(eventNumber: "2", eventText: NSMutableAttributedString().appendWith("The survivors are surrounded by the echoing coo of infant babble. Strange baby-faced birds circle overhead. Gripped with instinctual horror, the survivors break into a run!\n\nEach survivor rolls 1d10. The lowest scoring survivor (or survivors, in case of ties) becomes a straggler. If any survivor has ").appendWith(weight: .bold, "noisy").appendWith(" gear, -2 to their roll. Each straggler rolls 1d10.\n\nIf any survivor has a whip, they crack it, scattering many of the birds. In this case, each straggler adds +4 to their roll."), eventTitle: "3 | Cancer Pigeons", eventDie: "1d10", eventDieRoller1: "Straggler", eventResults1: [eventResult3a, eventResult3b, eventResult3c, eventResult3d])
        allHuntEvents.append(huntEvent3)
        
        let eventResult4a = EventResult(eventDieResult: "1 - 8", eventResultDescription: NSMutableAttributedString().appendWith("The hunt takes its toll. Powerful hunger pangs set in. All survivors gain a -1 speed token."))
        let eventResult4b = EventResult(eventDieResult: "9 - 14", eventResultDescription: NSMutableAttributedString().appendWith("You manage to stave off the terrible hunger."))
        let eventResult4c = EventResult(eventDieResult: "15+", eventResultDescription: NSMutableAttributedString().appendWith("Everyone is invigorated by their snack. Each survivor gains +1 survival."))
        let huntEvent4 = HuntEvent(eventNumber: "3", eventText: NSMutableAttributedString().appendWith("The path ahead is arid and dead. You may have survivors gain +1 courage and press on. Otherwise, roll again on the hunt event table before moving on the hunt board.\n\nIf you press on, your stomachs grumble in the dark as you stumble forward. The survivors pool their supplies. The event revealer rolls 1d10 and adds +2 to their roll for each consumable gear or resource the group has."), eventTitle: "4 | Famine", eventDie: "1d10", eventDieRoller1: "Event Revealer", eventResults1: [eventResult4a, eventResult4b, eventResult4c])
        allHuntEvents.append(huntEvent4)
        
        let eventResult5a = EventResult(eventDieResult: "1", eventResultDescription: NSMutableAttributedString().appendWith("The event revealer contracts a flesh-eating disease while brushing past the giant boils! A random limb is affected and must be amputated immediately. Roll 1d10, 1-5: arms, 6-10: legs. Suffer the ").appendWith(weight: .bold, "dismembered").appendWith(" severe injury at this location."))
        let eventResult5b = EventResult(eventDieResult: "2 - 3", eventResultDescription: NSMutableAttributedString().appendWith("If any survivor is ").appendWith(weight: .bold, "insane").appendWith(", they imagine the flesh fields are attacking! They become hysterical, flailing and tangling themselves in the thick hair. Each ").appendWith(weight: .bold, "insane").appendWith(" survivor suffers monster level event damage to a random location."))
        let eventResult5c = EventResult(eventDieResult: "4 - 7", eventResultDescription: NSMutableAttributedString().appendWith("It's hot and gross, but the survivors pass through the flesh fields with no complications."))
        let eventResult5d = EventResult(eventDieResult: "8 - 9", eventResultDescription: NSMutableAttributedString().appendWith("The event revealer makes the best of a bad situation and cuts a portion of the flesh free. Gain 1 ").appendWith(weight: .bold, "hide").appendWith(" basic resource."))
        let eventResult5e = EventResult(eventDieResult: "10+", eventResultDescription: NSMutableAttributedString().appendWith("Each survivor harvests 1 ").appendWith(weight: .bold, "hide").appendWith(" basic resource from the flesh fields."))
        let huntEvent5 = HuntEvent(eventNumber: "4", eventText: NSMutableAttributedString().appendWith("Ahead, the stone faces on the ground give way to a field of man-sized, fleshy boils sprouting thick black hair. The sinuous terrain radiates moist heat. As they travel, every survivor suffers heat exhaustion, losing 1 survival.\n\nThe event revealer rolls 1d10. If any survivor has a sickle, they help clear a path by cutting back the hair. Add +4 to the die roll."), eventTitle: "5 | Flesh Fields", eventDie: "1d10", eventDieRoller1: "Event Revealer", eventResults1: [eventResult5a, eventResult5b, eventResult5c, eventResult5d, eventResult5e])
        allHuntEvents.append(huntEvent5)
        
        let huntEvent6 = HuntEvent(eventNumber: "5", eventText: NSMutableAttributedString().appendWith("The survivors come upon a faceless statue holding a shining lantern. Basking in the warm light, the survivors are renewed. Each survivor gains 1 survival.\n\nIf the settlement has ").appendWith(weight: .bold, "Sculpture").appendWith(", the survivors deeply appreciate the artist's subtle craftsmanship. Each survivor rolls 1d10. Gain that many survival and +1 understanding.\n\nThe survivors may rest here longer. If they do, each survivor heals all injury levels and lost armor points on 1 hit location. However, they lose track of their quarry. Move the quarry 1 space away from the survivors on the hunt board. If a survivor heals more than 5 lost armor points this way, they stare into the shining light for too long and gain 1 random disorder.\n\nIf all survivors are ").appendWith(weight: .bold, "insane").appendWith(", they cannot rest longer."), eventTitle: "6 | Faceless Statue", eventDie: "N/A", eventDieRoller1: "N/A", eventResults1: [])
        allHuntEvents.append(huntEvent6)
        
        let eventResult7a = EventResult(eventDieResult: "1", eventResultDescription: NSMutableAttributedString().appendWith("With a muffled scream, you disappear into the ground. You manage to grab hold of a precarious ledge above the gaping maw. Lose all survival as you desperately climb up to safety. If you had none, you fall. Bones crunch between stone teeth. You are devoured whole. Dead."))
        let eventResult7b = EventResult(eventDieResult: "2 - 5", eventResultDescription: NSMutableAttributedString().appendWith("You scramble, but your leg is caught in the terrible maw. Suffer 2 event damage to the legs."))
        let eventResult7c = EventResult(eventDieResult: "6 - 9", eventResultDescription: NSMutableAttributedString().appendWith("You manage to leap away in time!"))
        let eventResult7d = EventResult(eventDieResult: "10+", eventResultDescription: NSMutableAttributedString().appendWith("Burp! Gurgle! The floor vomits a shiny piece of scrap. Gain 1 ").appendWith(weight: .bold, "broken lantern").appendWith(" basic resource."))
        let huntEvent7 = HuntEvent(eventNumber: "6", eventText: NSMutableAttributedString().appendWith("The ground suddenly splits and a gaping stone mouth attempts to devour the event revealer whole! The event revealer rolls 1d10.\n\nIf another survivor has a whip, they throw a line to the event revealer. Add +4 to your roll."), eventTitle: "7 | Hungry Ground", eventDie: "1d10", eventDieRoller1: "Event Revealer", eventResults1: [eventResult7a, eventResult7b, eventResult7c, eventResult7d])
        allHuntEvents.append(huntEvent7)
        
        let eventResult8a = EventResult(eventDieResult: "1 - 3", eventResultDescription: NSMutableAttributedString().appendWith("The fog around you turns black and fills with shapes of tormented faces. You are driven to madness. Gain 1 random disorder."))
        let eventResult8b = EventResult(eventDieResult: "4 - 6", eventResultDescription: NSMutableAttributedString().appendWith("The fog grows soupy and begins to wail. You plug your ears with your fingers, but it's hopeless. Suffer monster level brain event damage."))
        let eventResult8c = EventResult(eventDieResult: "7 - 9", eventResultDescription: NSMutableAttributedString().appendWith("You stick your thumbs into your ears and break into a run, leaving the wailing smoke."))
        let eventResult8d = EventResult(eventDieResult: "10+", eventResultDescription: NSMutableAttributedString().appendWith("Mimicking the disturbing smoke, you calmly start to wail with it. Gain +2 insanity."))
        let huntEvent8 = HuntEvent(eventNumber: "7", eventText: NSMutableAttributedString().appendWith("A constant moan follows the survivors. Eventually, they enter an area shrouded in thick fog and the wailing reaches a fevered pitch.\n\nEvery ").appendWith(weight: .bold, "non-deaf").appendWith(" survivor rolls 1d10. If all survivors are ").appendWith(weight: .bold, "deaf").appendWith(", they continue along, heedless to the cacophony: end this event. The lowest scoring survivor (or survivors, in case of ties) becomes a straggler. Each straggler rolls 1d10. If any survivor has ").appendWith(weight: .bold, "noisy").appendWith(" gear, the straggler adds +2 to their roll.\n\nIf any survivor has ").appendWith(weight: .bold, "noisy").appendWith(" gear, and the settlement has ").appendWith(weight: .bold, "Drums").appendWith(", they counter the wails with a tune from home. Do not roll on the table and each survivor gains +2 insanity and +2 survival."), eventTitle: "8 | Wailing Smoke", eventDie: "1d10", eventDieRoller1: "Straggler", eventResults1: [eventResult8a, eventResult8b, eventResult8c, eventResult8d])
        allHuntEvents.append(huntEvent8)
        
        let eventResult9a = EventResult(eventDieResult: "1 - 3", eventResultDescription: NSMutableAttributedString().appendWith("The light is overpowering. Your fragile mind cannot understand its soulless words. Gain 1 random disorder."))
        let eventResult9b = EventResult(eventDieResult: "4 - 6", eventResultDescription: NSMutableAttributedString().appendWith("You wander through the light, bathed in a warm, awful feeling. You don't find anything other than exposure. Suffer monster level event damage to a random hit location."))
        let eventResult9c = EventResult(eventDieResult: "9+", eventResultDescription: NSMutableAttributedString().appendWith("Something about the light stirs you, and your resolve intensifies. Gain +1 survival"))
        let huntEvent9 = HuntEvent(eventNumber: "8", eventText: NSMutableAttributedString().appendWith("A golden light blinds the survivors, stopping them in their tracks. The light shines from a single source. The event revealer is compelled to ").appendWith(weight: .bold, "investigate").appendWith(". They gain +1 courage and roll 1d10.\n\nIf the event revealer is ").appendWith(weight: .bold, "blind").appendWith(", they walk in the wrong direction and gain +3 insanity. Roll again on the hunt event table and do not investigate the light."), eventTitle: "9 | Golden Light", eventDie: "1d10", eventDieRoller1: "Event Revealer - Investigate", eventResults1: [eventResult9a, eventResult9b, eventResult9c])
        allHuntEvents.append(huntEvent9)
        
        let huntEvent10 = HuntEvent(eventNumber: "9", eventText: NSMutableAttributedString().appendWith("This event cannot be rerolled or avoided in any way.\n\nThe ground quakes and cracks beneath the survivors. A colossal worm bursts from below, its skin a mosaic of screaming faces. The mere sight of it is maddening.\n\nAll survivors gain 1 random disorder and must spend 1 survival or be devoured whole. If any survivor has ").appendWith(weight: .bold, "noisy").appendWith(" gear, the Harvester is drawn to the sound and they are instantly devoured. Nothing can save them.\n\nThe creature is so horrifying that the survivors' brains erase the experience from their memories. Do not gain the benefits of your death principle."), eventTitle: "10 | Harvester", eventDie: "N/A", eventDieRoller1: "N/A", eventResults1: [])
        allHuntEvents.append(huntEvent10)
        
        let eventResult11a = EventResult(eventDieResult: "1 - 3", eventResultDescription: NSMutableAttributedString().appendWith("You discover just how sickening playing with feces is. Lose 1 survival and roll again on the hunt event table before moving on the hunt board."))
        let eventResult11b = EventResult(eventDieResult: "4 - 6", eventResultDescription: NSMutableAttributedString().appendWith("The dropping tell a story. You are on the right track. Gain +1 survival."))
        let eventResult11c = EventResult(eventDieResult: "7+", eventResultDescription: NSMutableAttributedString().appendWith("You know these droppings well. You may skip the next hunt space. If this move begins the showdown, the survivors ").appendWith(weight: .bold, "ambush").appendWith(" their quarry"))
        let eventResult11d = EventResult(eventDieResult: "1 - 3", eventResultDescription: NSMutableAttributedString().appendWith("It seems you weren't the only one with this idea! You attempt to cough out the refuse, but your mouth is full of wriggling parasites. They burrow upwards through your nasal cavity into your brain. From now on, you always feel slightly dizzy. Suffer -1 permanent evasion.\n\nIn addition, if you have the ").appendWith(weight: .bold, "Quixotic").appendWith(" disorder, the parasites savor the unique neural activity of your brain, feeding relentlessly and excreting waste which further fuels your madness. Gain +10 insanity and the ").appendWith(weight: .bold, "Immortal").appendWith(" disorder. Your ").appendWith(weight: .bold, "Quixotic").appendWith(" disorder can never be removed for any reason."))
        let eventResult11e = EventResult(eventDieResult: "4 - 6", eventResultDescription: NSMutableAttributedString().appendWith("It's repulsive. Your title becomes ").appendWith(color: UIColor(red:0.16, green:0.66, blue:0.79, alpha:1.0), "'Scat Man'").appendWith(". Everyone in the settlement must call you by that name from now on."))
        let eventResult11f = EventResult(eventDieResult: "7+", eventResultDescription: NSMutableAttributedString().appendWith("There was something quite special about the feces. Gain +1 speed and +1 strength token."))
        let huntEvent11 = HuntEvent(eventNumber: "10", eventText: NSMutableAttributedString().appendWith("The survivors find some monster droppings, like those of their quarry. The event revealer chooses to either ").appendWith(weight: .bold, "investigate").appendWith(" or ").appendWith(weight: .bold, "consume").appendWith(" the droppings (choose only one).\n\nIf the event revealer ").appendWith(weight: .bold, "investigates").appendWith(", gain +1 understanding and roll 1d10 on the first table.\n\nIf the event revealer ").appendWith(weight: .bold, "consumes").appendWith(", gain +1 courage and roll 1d10 on the second table."), eventTitle: "11 | Monster Droppings", eventDie: "1d10", eventDieRoller1: "Event revealer - Investigate", eventDieRoller2: "Event Revealer - Consume", eventResults1: [eventResult11a, eventResult11b, eventResult11c], eventResults2: [eventResult11d, eventResult11e, eventResult11f], numEventTables: 2)
        allHuntEvents.append(huntEvent11)
        
        let huntEvent12 = HuntEvent(eventNumber: "11", eventText: NSMutableAttributedString().appendWith("The survivors collectively feel a heightened level of anticipation. Their goal is close at hand. The event revealer gains +1 courage! The survivors may skip the next hunt space. If this movement starts the showdown, the survivors ").appendWith(weight: .bold, "ambush").appendWith(" their quarry."), eventTitle: "12 | Destiny-Bound", eventDie: "N/A", eventDieRoller1: "", eventResults1: [])
        allHuntEvents.append(huntEvent12)
        
        let eventResult13a = EventResult(eventDieResult: "1 - 5", eventResultDescription: NSMutableAttributedString().appendWith("The depths of your misery are deeper than you could have ever imagined. Gain disorders until you have 3 of them. Lose all survival."))
        let eventResult13b = EventResult(eventDieResult: "6+", eventResultDescription: NSMutableAttributedString().appendWith("You sink to the bottom of your misery and scrape its very foundations, hungry for more! You uncover a primal rage surrounding a core of serene calm. Gain +1 understanding and the ").appendWith(weight: .bold, "Rageholic").appendWith(" disorder."))
        let eventResult13c = EventResult(eventDieResult: "1 - 5", eventResultDescription: NSMutableAttributedString().appendWith("You rise, silent tears streaming down your face. With the settlement at your back, you are ready to face the darkness. Gain +1 courage and +1d10 survival."))
        let eventResult13d = EventResult(eventDieResult: "6+", eventResultDescription: NSMutableAttributedString().appendWith("You briefly touch the bottom of your misery and return to full awareness with new experiences to share. If any survivors return to the settlement this year, gain +2 endeavors."))
        let huntEvent13 = HuntEvent(eventNumber: "12", eventText: NSMutableAttributedString().appendWith("The event revealer falls to their knees, sobbing uncontrollably. They've simply had too much. They lose 1d10 survival and gain 1 random disorder.\n\nIf the settlement has ").appendWith(weight: .bold, "Accept Darkness").appendWith(", the event revealer embraces their despair. Roll 1d10 on the first event table.\n\nIf the settlement has ").appendWith(weight: .bold, "Collective Toil").appendWith(", they slowly pull themselves to their feet, promising to never give up hope. Roll 1d10 on the second event table."), eventTitle: "13 | Overload", eventDie: "1d10", eventDieRoller1: "Event Revealer", eventDieRoller2: "Event Revealer", eventResults1: [eventResult13a, eventResult13b], eventResults2: [eventResult13c, eventResult13d], numEventTables: 2)
        allHuntEvents.append(huntEvent13)
        
        let huntEvent14 = HuntEvent(eventNumber: "13", eventText: NSMutableAttributedString().appendWith("The survivors encounter a bewitching, barefoot waif with soot-covered feet. If you already rolled this event on this hunt, or if all survivors are ").appendWith(weight: .bold, "insane").appendWith(", she turns her back and disappears into the darkness. Roll again on the hunt event table before moving on the hunt board.\n\nOtherwise, exclaiming wildly at the survivors, the woman's presence fills everyone with the alien feeling of hope. All survivors gain +1 courage and +1 understanding.\n\nIf the settlement has ").appendWith(weight: .bold, "Hovel").appendWith(", she snaps her fingers and ages before their eyes! A chill passes over the survivors. Their bodies and armor spontaneously knit themselves back together. Heal all injury levels and lost armor points. Then, she pulls a random survivor aside and whispers secrets of the upcoming hunt. That survivor gains +1 accuracy token."), eventTitle: "14 | Chance Encounter", eventDie: "N/A", eventDieRoller1: "N/A", eventResults1: [])
        allHuntEvents.append(huntEvent14)
        
        let eventResult15a = EventResult(eventDieResult: "1 - 2", eventResultDescription: NSMutableAttributedString().appendWith("With a terrible crash, the steel jaws of the man-trap cleanly sever your foot. Suffer the ").appendWith(weight: .bold, "dismembered leg").appendWith(" severe injury."))
        let eventResult15b = EventResult(eventDieResult: "3 - 6", eventResultDescription: NSMutableAttributedString().appendWith("Mangled leg. Destroy all armor at the legs location, then suffer 1 event damage to the legs."))
        let eventResult15c = EventResult(eventDieResult: "7 - 9", eventResultDescription: NSMutableAttributedString().appendWith("The trap is quite old and weak. Suffer 1 event damage to the legs."))
        let eventResult15d = EventResult(eventDieResult: "10+", eventResultDescription: NSMutableAttributedString().appendWith("The event revealer's foot knocks into the trap, giving everyone a scare! However, it was already sprung., leaving an unfortunate prize in its jaws. Gain 1 random basic resource."))
        let huntEvent15 = HuntEvent(eventNumber: "14", eventText: NSMutableAttributedString().appendWith("The event revealer springs a terrible trap! Roll 1d10."), eventTitle: "15 | Man Trap", eventDie: "1d10", eventDieRoller1: "Event Revealer", eventResults1: [eventResult15a, eventResult15b, eventResult15c, eventResult15d])
        allHuntEvents.append(huntEvent15)
        
        let huntEvent16 = HuntEvent(eventNumber: "15", eventText: NSMutableAttributedString().appendWith("Your miserable sleep is plagued with mind-bending nightmares. Each survivor rolls 1d10. If the result is greater than their insanity, they learn something from the waking horror and gain +1 understanding. Otherwise they gain 1 random disorder.\n\nIf any survivor is a savior or has the ").appendWith(weight: .bold, "Extra Sense").appendWith(" fighting art, they disappear into the dream, emerging from the darkness hours later. They gain +4 Hunt XP and a random basic resource."), eventTitle: "16 | Night Terrors", eventDie: "N/A", eventDieRoller1: "N/A", eventResults1: [])
        allHuntEvents.append(huntEvent16)
        
        let eventResult17a = EventResult(eventDieResult: "1", eventResultDescription: NSMutableAttributedString().appendWith("The face is identical to your own. Spend 1d5 survival or reduce your understanding to 0."))
        let eventResult17b = EventResult(eventDieResult: "2 - 7", eventResultDescription: NSMutableAttributedString().appendWith("The face reminds you of someone dear. Your heart aches with loneliness. If your survival is greater than your insanity, suffer monster level brain event damage."))
        let eventResult17c = EventResult(eventDieResult: "8+", eventResultDescription: NSMutableAttributedString().appendWith("The face is your own but older and wiser. Gain +1 survival and +1 understanding."))
        let huntEvent17 = HuntEvent(eventNumber: "16", eventText: NSMutableAttributedString().appendWith("Amidst the sea of stone faces, one catches the event revealer's eye. They feel compelled to ").appendWith(weight: .bold, "investigate").appendWith(". Gain +1 courage and roll 1d10."), eventTitle: "17 | Face-to-Face", eventDie: "1d10", eventDieRoller1: "Event Revealer - Investigate", eventResults1: [eventResult17a, eventResult17b, eventResult17c])
        allHuntEvents.append(huntEvent17)
        
        let eventResult18a = EventResult(eventDieResult: "1 - 7", eventResultDescription: NSMutableAttributedString().appendWith("Try as you might, you cannot pull out the deeply-rooted weed."))
        let eventResult18b = EventResult(eventDieResult: "8+", eventResultDescription: NSMutableAttributedString().appendWith("You pull the weed free! It has enormous regenerative power. Each survivor rubs it on their skin and removes 1 permanent severe injury. Then the weed crumbles into dust in your hands."))
        let huntEvent18 = HuntEvent(eventNumber: "17", eventText: NSMutableAttributedString().appendWith("You find a strange plant growing from the eyes of a stone face. The event revealer tries to harvest it. Roll 1d10. If any survivor has a sickle, add +4 to their roll."), eventTitle: "18 | Dead Weed", eventDie: "1d10", eventDieRoller1: "Event Revealer", eventResults1: [eventResult18a, eventResult18b])
        allHuntEvents.append(huntEvent18)
        
        let eventResult19a = EventResult(eventDieResult: "1 - 2", eventResultDescription: NSMutableAttributedString().appendWith("You trip and fall into the bones of an ancient monster, smashing a piece of gear on the way down. Archive 1 piece of gear of your choice from your gear grid."))
        let eventResult19b = EventResult(eventDieResult: "3  - 5", eventResultDescription: NSMutableAttributedString().appendWith("Something unseen attacks you. Suffer 1 brain event damage."))
        let eventResult19c = EventResult(eventDieResult: "6 - 8", eventResultDescription: NSMutableAttributedString().appendWith("You bang into a giant stone face's nose! Suffer 1 head event damage"))
        let eventResult19d = EventResult(eventDieResult: "9+", eventResultDescription: NSMutableAttributedString().appendWith("You're not sure how, but you leave the darkness with your hands full. Gain 1 random basic resource."))
        let huntEvent19 = HuntEvent(eventNumber: "18", eventText: NSMutableAttributedString().appendWith("The survivors are enveloped in a steamy darkness that dims their lantern lights. They become separated from each other and hopelessly lost. If a survivor has the ").appendWith(weight: .bold, "Leader").appendWith(" fighting art, they boldly stride into the clammy darkness and gather everyone. Otherwise, each survivor rolls 1d10. The lowest scoring survivor (or survivors in case of ties), becomes a straggler. Each straggler rolls 1d10."), eventTitle: "19 | Exhalation of Darkness", eventDie: "1d10", eventDieRoller1: "Straggler", eventResults1: [eventResult19a, eventResult19b, eventResult19c, eventResult19d])
        allHuntEvents.append(huntEvent19)
        
        let huntEvent20 = HuntEvent(eventNumber: "19", eventText: NSMutableAttributedString().appendWith("As the survivors press forward, the air turns dry and the ground cracks. The survivors suffer heat exhaustion. Each survivor loses 1 survival. If they are wearing fur or heavy gear, they instead lose 1d5 survival.\n\nIf any survivor has a pickaxe, the survivors break open an interesting-looking vein in the cracked ground. Gain 1 ").appendWith(weight: .bold, "Iron").appendWith(" strange resource."), eventTitle: "20 | Dry Lands", eventDie: "N/A", eventDieRoller1: "N/A", eventResults1: [])
        allHuntEvents.append(huntEvent20)
        
        let eventResult21a = EventResult(eventDieResult: "1 - 3", eventResultDescription: NSMutableAttributedString().appendWith("Your nose begins to bleed. Suffer monster level brain event damage."))
        let eventResult21b = EventResult(eventDieResult: "4 - 7", eventResultDescription: NSMutableAttributedString().appendWith("The true meaning escapes you. Gain +1 insanity."))
        let eventResult21c = EventResult(eventDieResult: "8+", eventResultDescription: NSMutableAttributedString().appendWith("The drawings teach you a new way to fight monsters! Gain +2 survival and 1 random fighting art."))
        let huntEvent21 = HuntEvent(eventNumber: "20", eventText: NSMutableAttributedString().appendWith("Cowering in a cave, the survivors find strange drawings decorating the walls. They appear to contain a message. Any survivor with 3+ understanding may try to decipher the drawings by rolling 1d10. If the settlement has ").appendWith(weight: .bold, "Pictographs").appendWith(", every survivor may roll (regardless of their understanding) and add +4 to their rolls."), eventTitle: "21 | Drawings", eventDie: "1d10", eventDieRoller1: "Any survivor with 3+ understanding", eventResults1: [eventResult21a, eventResult21b, eventResult21c])
        allHuntEvents.append(huntEvent21)
        
        let huntEvent22 = HuntEvent(eventNumber: "21", eventText: NSMutableAttributedString().appendWith("The darkness above is suddenly alight with a storm of acid rain. It smells terrible, burns flesh, and forms hissing pools in the upturned mouths of the stone faces. All survivors suffer monster level event damage to every hit location as they scramble to find shelter.\n\nIf the settlement has ").appendWith(weight: .bold, "Sculpture").appendWith(", the survivors silently watch the storm erode the stone faces, erasing their features. They wonder exactly who or what repairs the broken faces - if there is such a thing. The survivors share a dark laugh, each gaining monster level survival.\n\nRoll 1d10. On a 6+, the storm moves homeward. Add the ").appendWith(weight: .bold, "Acid Storm").appendWith(" settlement event to the timeline next year."), eventTitle: "22 | Acid Rain", eventDie: "N/A", eventDieRoller1: "N/A", eventResults1: [])
        allHuntEvents.append(huntEvent22)
        
        let eventResult23a = EventResult(eventDieResult: "1 - 2", eventResultDescription: NSMutableAttributedString().appendWith("The instant it becomes wet, your hair turns stark white. Gain 1 random disorder."))
        let eventResult23b = EventResult(eventDieResult: "3 - 5", eventResultDescription: NSMutableAttributedString().appendWith("Your hair is wet. Congratulations."))
        let eventResult23c = EventResult(eventDieResult: "6 - 8", eventResultDescription: NSMutableAttributedString().appendWith("The water is bracing. Gain +1 understanding or remove a disorder of your choice."))
        let eventResult23d = EventResult(eventDieResult: "9+", eventResultDescription: NSMutableAttributedString().appendWith("The water is shockingly cold! It rushes over you like a tidal wave and leaves you awestruck. Set your instanity to 0 and remove all disorders."))
        let huntEvent23 = HuntEvent(eventNumber: "22", eventText: NSMutableAttributedString().appendWith("The survivors pass a forlorn fountain in the shape of a lion's face. A stream of crystal-clear water flows from its mouth. Each survivor consumes the water, gaining +1 survival and +1 courage. Any number of survivors may douse their head in the water and roll 1d10."), eventTitle: "23 | Clean Water", eventDie: "1d10", eventDieRoller1: "Any Survivor", eventResults1: [eventResult23a, eventResult23b, eventResult23c, eventResult23d])
        allHuntEvents.append(huntEvent23)
        
        let eventResult24a = EventResult(eventDieResult: "1 - 2", eventResultDescription: NSMutableAttributedString().appendWith("You yell out in pain and pull your hand back, revealing a bloody gash. Did the stone face just bite? Suffer monster level brain damage and monster level event arm damage."))
        let eventResult24b = EventResult(eventDieResult: "3 - 5", eventResultDescription: NSMutableAttributedString().appendWith("There's nothing. It was just a trick of the lantern light."))
        let eventResult24c = EventResult(eventDieResult: "6 - 8", eventResultDescription: NSMutableAttributedString().appendWith("More rocks - what did you expect? Gain 1 ").appendWith(weight: .bold, "Founding Stone").appendWith(" starting gear."))
        let eventResult24d = EventResult(eventDieResult: "9+", eventResultDescription: NSMutableAttributedString().appendWith("You pull out a masticated mass. Gain 1 random basic resource and 2 insanity."))
        let huntEvent24 = HuntEvent(eventNumber: "23", eventText: NSMutableAttributedString().appendWith("The survivors pass a stone face that appears to be holding something in its mouth. The event revealer ").appendWith(weight: .bold, "investigates").appendWith(". Gain +1 courage and roll 1d10."), eventTitle: "24 | Food from the Mouths of Others", eventDie: "1d10", eventDieRoller1: "Event Revealer - Investigate", eventResults1: [eventResult24a, eventResult24b, eventResult24c, eventResult24d])
        allHuntEvents.append(huntEvent24)
        
        let eventResult25a = EventResult(eventDieResult: "1", eventResultDescription: NSMutableAttributedString().appendWith("You're plucked from the ground and eaten whole. Dead. If the settlement has ").appendWith(weight: .bold, "Survival of the Fittest").appendWith(", you twist out of its mouth and land with a thud. Suffer the ").appendWith(weight: .bold, "broken arm").appendWith(" and").appendWith(weight: .bold, " broken leg").appendWith(" severe injuries, but do not die."))
        let eventResult25b = EventResult(eventDieResult: "2 - 4", eventResultDescription: NSMutableAttributedString().appendWith("Something snatches you in its great maw and chews you for 1 event damage to 1d5 random hit locations."))
        let eventResult25c = EventResult(eventDieResult: "5 - 6", eventResultDescription: NSMutableAttributedString().appendWith("The clamping jaws barely nip you! Suffer monster level event damage to a random hit location."))
        let eventResult25d = EventResult(eventDieResult: "7 - 9", eventResultDescription: NSMutableAttributedString().appendWith("You make yourself extra flat against the ground and avoid anything terrible."))
        let eventResult25e = EventResult(eventDieResult: "10+", eventResultDescription: NSMutableAttributedString().appendWith("You will never stop running from what you saw. Gain +1 permanent movement."))
        let huntEvent25 = HuntEvent(eventNumber: "24", eventText: NSMutableAttributedString().appendWith("An earsplitting bellow marks the passing of a truly titanic beast. All ").appendWith(weight: .bold, "non-deaf").appendWith(" survivors suffer monster level brain event damage. The survivors cower on the ground, lying as flat as possible and hoping they are simply too small to be worth eating.\n\nEach survivor rolls 1d10. The lowest scoring survivor (or survivors, in the case of ties) becomes a straggler. If any survivor has ").appendWith(weight: .bold, "noisy").appendWith(" gear, -2 to their roll."), eventTitle: "25 | Titans in the Dark", eventDie: "1d10", eventDieRoller1: "Straggler", eventResults1: [eventResult25a, eventResult25b, eventResult25c, eventResult25d, eventResult25e])
        allHuntEvents.append(huntEvent25)
        
        let eventResult26a = EventResult(eventDieResult: "1", eventResultDescription: NSMutableAttributedString().appendWith("You land with a sickening crunch, mangling your legs. Suffer the ").appendWith(weight: .bold, "broken leg").appendWith(" severe injury twice."))
        let eventResult26b = EventResult(eventDieResult: "2 - 3", eventResultDescription: NSMutableAttributedString().appendWith("Your leg breaks your fall. Suffer the ").appendWith(weight: .bold, "broken leg").appendWith(" severe injury."))
        let eventResult26c = EventResult(eventDieResult: "4 - 6", eventResultDescription: NSMutableAttributedString().appendWith("You land at the bottom with a loud thud. Suffer 2 event damage to a random hit location and archive all ").appendWith(weight: .bold, "fragile").appendWith(" gear in your gear grid."))
        let eventResult26d = EventResult(eventDieResult: "7 - 9", eventResultDescription: NSMutableAttributedString().appendWith("You land at the bottom with a soft thud. Suffer 1 event damage to a random hit location."))
        let eventResult26e = EventResult(eventDieResult: "10+", eventResultDescription: NSMutableAttributedString().appendWith("You manage to grab the edge of the pit and escape unharmed."))
        let huntEvent26 = HuntEvent(eventNumber: "25", eventText: NSMutableAttributedString().appendWith("The ground beneath the event revealer's feet gives way and they plummet into a pit below. The event revealer rolls 1d10.\n\nIf another survivor has a whip, they throw you a line in time; do not roll on the table.\n\nIf the event revealer has the ").appendWith(weight: .bold, "Tumble").appendWith(" fighting art, they nimbly catch a ledge and haul themselves up; gain +1 speed token and do not roll on the table."), eventTitle: "26 | Pit", eventDie: "1d10", eventDieRoller1: "Event Revealer", eventResults1: [eventResult26a, eventResult26b, eventResult26c, eventResult26d, eventResult26e])
        allHuntEvents.append(huntEvent26)
        
        let eventResult27a = EventResult(eventDieResult: "1 - 5", eventResultDescription: NSMutableAttributedString().appendWith("When you wake, your genitals have been stolen. In their place is nothing but smooth skin. Suffer the ").appendWith(weight: .bold, "destroyed genitals").appendWith(" severe injury"))
        let eventResult27b = EventResult(eventDieResult: "6+", eventResultDescription: NSMutableAttributedString().appendWith("You wake with a start, terrified to find menacing pincers approaching. Your defenses are quick. Without thinking, you wallop the insect crawling on your pants, suffering 1 event damage to the waist"))
        let huntEvent27 = HuntEvent(eventNumber: "26", eventText: NSMutableAttributedString().appendWith("Exhausted, the survivors rest. During their fitful sleep, a small insect approaches undetected. Choose 1 random male survivor and roll on the table. If there are no male survivors, nothing happens.\n\nIf the chosen survivor has the ").appendWith(weight: .bold, "Unconscious Fighter").appendWith(" fighting art, they crush the bug while still snoring; do not roll on the table. They wake, confused, with a random ").appendWith(weight: .bold, "vermin").appendWith(" resource in their hands."), eventTitle: "27 | Man Stealers", eventDie: "1d10", eventDieRoller1: "Random male survivor", eventResults1: [eventResult27a, eventResult27b])
        allHuntEvents.append(huntEvent27)
        
        let eventResult28a = EventResult(eventDieResult: "1 - 5", eventResultDescription: NSMutableAttributedString().appendWith("The trollbird makes a terrible racket, alerting the monster. All survivors gain +1 understanding. At the start of the showdown, the monster ").appendWith(weight: .bold, "ambushes").appendWith(" the survivors."))
        let eventResult28b = EventResult(eventDieResult: "6+", eventResultDescription: NSMutableAttributedString().appendWith("The trollbird mocks and distracts the monster as the survivors sneak up. All survivors gain +1 insanity. At the start of the showdown, the survivors ").appendWith(weight: .bold, "ambush").appendWith(" the monster."))
        let huntEvent28 = HuntEvent(eventNumber: "27", eventText: NSMutableAttributedString().appendWith("A rumpled, unsightly bird stands in the survivors' path. Its beady, wet eyes blink expectantly and it calls out with an eerie human chuckle. The survivors may archive 1 ").appendWith(weight: .bold, "consumable").appendWith(" item or gear, offering it to the trollbird. If any survivor is ").appendWith(weight: .bold, "insane").appendWith(", they must feed the trollbird if able. If they feed the trollbird, it hops off with a terrible cackle.\n\nIf they don't feed the trollbird, it follows the survivors on their hunt, constantly mocking them with its chuckle. Roll 1d10. If any survivor has the ").appendWith(weight: .bold, "Coprolalia").appendWith(" disorder, they curse at the bird and make vigorous and vulgar gestures. The bird is impressed. Add +3 to your roll"), eventTitle: "28 | Trollbird", eventDie: "1d10", eventDieRoller1: "Event Revealer", eventResults1: [eventResult28a, eventResult28b])
        allHuntEvents.append(huntEvent28)
        
        let eventResult29a = EventResult(eventDieResult: "1 - 2", eventResultDescription: NSMutableAttributedString().appendWith("The creature raises the object to its mouth and eats it. It's gone. Archive the gear card."))
        let eventResult29b = EventResult(eventDieResult: "3 - 6", eventResultDescription: NSMutableAttributedString().appendWith("The creature refuses the gear and stares at you with a single, large eye. Suffer 1d10 brain event damage."))
        let eventResult29c = EventResult(eventDieResult: "7 - 8", eventResultDescription: NSMutableAttributedString().appendWith("The creature unhinges its jaw and eats the piece of gear. In return, it hands you a shining shield. Gain the ").appendWith(weight: .bold, "Steel Shield").appendWith(" rare gear."))
        let eventResult29d = EventResult(eventDieResult: "9+", eventResultDescription: NSMutableAttributedString().appendWith("The creature unhinges its jaw and eats the piece of gear. In return, it hands you a shining sword. Gain the ").appendWith(weight: .bold, "Steel Sword").appendWith(" rare gear"))
        let huntEvent29 = HuntEvent(eventNumber: "28", eventText: NSMutableAttributedString().appendWith("The survivors cross paths with a tall, unnaturally thin man in a hooded robe. Where his feet strike the ground, sparks illuminate his path.\n\nEach survivor with 3+ courage may give him one piece of gear from their gear grid and roll on the table. If they have the ").appendWith(weight: .bold, "Honorable").appendWith(" disorder, add +3 to their roll."), eventTitle: "29 | Dark Blacksmith", eventDie: "1d10", eventDieRoller1: "Any survivor with 3+ courage", eventResults1: [eventResult29a, eventResult29b, eventResult29c, eventResult29d])
        allHuntEvents.append(huntEvent29)
        
        let eventResult30a = EventResult(eventDieResult: "1", eventResultDescription: NSMutableAttributedString().appendWith("Your foot gets stuck and you quickly begin to sink into the ground. After a struggle you manage to break free. If you had leg armor, it is lost in the muck. Spend 3 survival or archive the gear."))
        let eventResult30b = EventResult(eventDieResult: "2 - 5", eventResultDescription: NSMutableAttributedString().appendWith("Mired, you struggle to break free. Roll again on this table or spend 1 survival to escape."))
        let eventResult30c = EventResult(eventDieResult: "6 - 9", eventResultDescription: NSMutableAttributedString().appendWith("You escape without incident."))
        let eventResult30d = EventResult(eventDieResult: "10+", eventResultDescription: NSMutableAttributedString().appendWith("You find something gross while drudging through the rot. Gain 1 random basic resource."))
        let huntEvent30 = HuntEvent(eventNumber: "29", eventText: NSMutableAttributedString().appendWith("The stone faces start to give under the survivors' feet. They are bloated and smell terrible. Each survivor rolls 1d10."), eventTitle: "30 | Rotten Faces", eventDie: "1d10", eventDieRoller1: "Each survivor", eventResults1: [eventResult30a, eventResult30b, eventResult30c, eventResult30d])
        allHuntEvents.append(huntEvent30)
        
        let eventResult31a = EventResult(eventDieResult: "1", eventResultDescription: NSMutableAttributedString().appendWith("A colossal finger descends from above, crushing a random survivor. They suffer 2 event damage to every hit location."))
        let eventResult31b = EventResult(eventDieResult: "2 - 4", eventResultDescription: NSMutableAttributedString().appendWith("A random survivor tears off hysterically along a branch in the path"))
        let eventResult31c = EventResult(eventDieResult: "5 - 7", eventResultDescription: NSMutableAttributedString().appendWith("The path twists and turns dizzyingly into the dark. All survivors suffer 1 brain event damage and the event revealer rolls again on this table, adding +2 to their roll."))
        let eventResult31d = EventResult(eventDieResult: "8 - 9", eventResultDescription: NSMutableAttributedString().appendWith("The path leads the survivors to a large stone face with lanterns for eyes. Inside its open mouth is a bounty. Each survivor gains 1 random basic resource."))
        let eventResult31e = EventResult(eventDieResult: "10+", eventResultDescription: NSMutableAttributedString().appendWith("The path leads to the beast you are hunting! The survivors ").appendWith(weight: .bold, "ambush").appendWith(" the monster.\n\nIf any survivor has the ").appendWith(weight: .bold, "Honorable").appendWith(" disorder, they realize the folly of their ways, and may remove the disorder. If any survivors remain ").appendWith(weight: .bold, "Honorable").appendWith(" they announce their presence to the monster; the monster ").appendWith(weight: .bold, "ambushes").appendWith(" the survivors instead."))
        let huntEvent31 = HuntEvent(eventNumber: "30", eventText: NSMutableAttributedString().appendWith("The survivors stop at the head of a path. Small lanterns twinkle, marking its edges.\n\nThe event revealer decides whether or not the survivors follow the path. If the event revealer is ").appendWith(weight: .bold, "insane").appendWith(", they must. If the survivors follow the path, the event revealer gains +1 understanding, then rolls 1d10 and adds their understanding.\n\nOtherwise, roll again on the hunt event table before moving further on the hunt board."), eventTitle: "31 | Strange Path", eventDie: "1d10", eventDieRoller1: "Event Revealer", eventResults1: [eventResult31a, eventResult31b, eventResult31c, eventResult31d, eventResult31e])
        allHuntEvents.append(huntEvent31)
        
        let huntEvent32 = HuntEvent(eventNumber: "31", eventText: NSMutableAttributedString().appendWith("The event revealer is devastated by a piercing cacophony in their head. Roll 1d10. If the result is less than or equal to their current insanity, they go mad, lashing out at their compatriots! Each other survivor suffers 1 event damage to a random hit location before the event revealer regains control of themselves.\n\nIf the event revealer has the ").appendWith(weight: .bold, "Crazed").appendWith(" fighting art, they gain insight from their ordeal. Gain +10 insanity and +2 understanding."), eventTitle: "32 | Sudden Madness", eventDie: "N/A", eventDieRoller1: "N/A", eventResults1: [])
        allHuntEvents.append(huntEvent32)
        
        let huntEvent33 = HuntEvent(eventNumber: "32", eventText: NSMutableAttributedString().appendWith("The event revealer trips over a protuding nose in the ground. The lips of a stone face begin to move!\n\nIf the event revealer has no name, the lips stop moving and nothing else happens. Otherwise, the lips seductively whisper the survivor's name.\n\nIf the event revealer is ").appendWith(weight: .bold, "insane").appendWith(", they are drawn in, savagely kissing the face. Repulsed and outraged, the other survivors suffer 1 brain event damage before pulling the crazed survivor from the ground and moving on.\n\nIf the event revealer is not ").appendWith(weight: .bold, "insane").appendWith(", they gain +1 understanding, feeling on the cusp of learning something.\n\nIf any survivor has the ").appendWith(weight: .bold, "Marrow Hunger").appendWith(" impairment, the face secretly whispers their life's purpose. They gain +1 permanent strength. Add the ").appendWith(weight: .bold, "Murder").appendWith(" settlement event to the timeline next year."), eventTitle: "33 | It Whispers Your Name", eventDie: "N/A", eventDieRoller1: "N/A", eventResults1: [])
        allHuntEvents.append(huntEvent33)
        
        let huntEvent34 = HuntEvent(eventNumber: "33", eventText: NSMutableAttributedString().appendWith("Each survivor rolls 1d10. The lowest-rolling survivor (or survivors, in case of ties), becomes a straggler. If any survivor (or survivors) has the ").appendWith(weight: .bold, "Anxiety").appendWith(" disorder, they are the straggler. Do not roll.\n\nThe straggler is lost in a moment of profound self doubt. They slip, not having the will to catch themselves, and tumble off a steep hill of stone faces. They land awkwardly with a crunch, suffering the ").appendWith(weight: .bold, "broken leg").appendWith(" sever injury. Sobbing to themselves, they come to grips with just how terrible their life is and gain +1 understanding.\n\nIf the straggler has the ").appendWith(weight: .bold, "Binge Eating").appendWith(" disorder, they wipe away their tears and reach out to a nearby critter, instinctually cramming it into their mouth for comfort. Draw 1 random vermin resource and ").appendWith(weight: .bold, "consume").appendWith(" it."), eventTitle: "34 | Crippling Misery", eventDie: "N/A", eventDieRoller1: "N/A", eventResults1: [])
        allHuntEvents.append(huntEvent34)
        
        let eventResult35a = EventResult(eventDieResult: "1 - 5", eventResultDescription: NSMutableAttributedString().appendWith("You try to enter the ruined lantern hoard, but you are overcome with fear, keeling over and vomiting everywhere. When you rise, you find yourself physically incapable of pushing forward any longer. Gain the ").appendWith(weight: .bold, "Apathetic").appendWith(" disorder."))
        let eventResult35b = EventResult(eventDieResult: "6+", eventResultDescription: NSMutableAttributedString().appendWith("You are repelled by the ruined lantern hoard, but linger just long enough to grab a pair of insects scurrying within it. That's as close as you're comfortable going. Gain 2 vermin resources of your choice."))
        let huntEvent35 = HuntEvent(eventNumber: "34", eventText: NSMutableAttributedString().appendWith("The survivors come across the shattered ruins of a small settlement. Ashen corpses dot the ruins, disintegrating at the slightest touch. An extinguished lantern oven stands intact at the center of the settlement.\n\nThe event revealer rolls 1d10 and adds their understanding. If the result is 5+, gain the ").appendWith(weight: .bold, "Lantern Oven").appendWith(" innovation. If the settlement already has this innovation, the event revealer harvests a ").appendWith(weight: .bold, "broken lantern").appendWith(" basic resource from the remains.\n\nIf the settlement has ").appendWith(weight: .bold, "Song of the Brave").appendWith(", the group may nominate a brave survivor to ").appendWith(weight: .bold, "investigate").appendWith(" the ruins of the settlement's lantern hoard. They gain +1 courage and roll 1d10."), eventTitle: "35 | Broken Lantern Oven", eventDie: "1d10", eventDieRoller1: "Nominated Survivor", eventResults1: [eventResult35a, eventResult35b])
        allHuntEvents.append(huntEvent35)
        
        let huntEvent36 = HuntEvent(eventNumber: "35", eventText: NSMutableAttributedString().appendWith("The survivors rush forward, feeling their quarry close at hand. Skip the next hunt space. If this movement begins the showdown, the survivors ").appendWith(weight: .bold, "ambush").appendWith(" their quarry. If any survivor has ").appendWith(weight: .bold, "noisy").appendWith(" gear, the survivors do not ambush. Start the showdown normally."), eventTitle: "36 | On the Trail", eventDie: "N/A", eventDieRoller1: "N/A", eventResults1: [])
        allHuntEvents.append(huntEvent36)
        
        let huntEvent37 = HuntEvent(eventNumber: "36", eventText: NSMutableAttributedString().appendWith("The survivors are hopelessly lost in the unbroken darkness. Move the survivors 2 spaces back on the hunt board."), eventTitle: "37 | Lost", eventDie: "N/A", eventDieRoller1: "N/A", eventResults1: [])
        allHuntEvents.append(huntEvent37)
        
        let eventResult38a = EventResult(eventDieResult: "1 - 6", eventResultDescription: NSMutableAttributedString().appendWith("The survivors quickly fall behind the majestic beast. Move 1 space away from the quarry on the hunt board."))
        let eventResult38b = EventResult(eventDieResult: "7 - 14", eventResultDescription: NSMutableAttributedString().appendWith("The Gregalope is far too fast. It's gone before you know it."))
        let eventResult38c = EventResult(eventDieResult: "15 - 16", eventResultDescription: NSMutableAttributedString().appendWith("The survivors lose sight of the Gregalope but discover a hidden path. You may re-roll the next result on the hunt event table."))
        let eventResult38d = EventResult(eventDieResult: "17+", eventResultDescription: NSMutableAttributedString().appendWith("Just before it leaps out of view, the Gregalope bows its mighty horns. The experience changes the exhausted event revealer. They gain +1 permanent movement."))
        let huntEvent38 = HuntEvent(eventNumber: "37", eventText: NSMutableAttributedString().appendWith("A massive Gregalope stands astride the horizon, its ancient body bloated with tumors and scar tissue. Its milky eyes catch sight of the survivors and it bounds away. Driven by a sudden desire, the survivors give chase. The event revealer rolls 1d10 and adds their movement to the roll.\n\nIf any survivor has the ").appendWith(weight: .bold, "Strategist").appendWith(" fighting art, they may corner the Gregalope at a giant stone face instead of giving chase. If they do, end the hunt immediately. Start a showdown with a level 2 Screaming Antelope, using its setup rules. In addition, place a ").appendWith(weight: .bold, "Giant Stone Face").appendWith(" adjacent to the monster and give the monster the Butcher's ").appendWith(weight: .bold, "Berserker").appendWith(" trait card. If the survivors prevail, gain the normal showdown rewards and 3 additional Screaming Antelope resources."), eventTitle: "38 | Gregalope", eventDie: "1d10", eventDieRoller1: "Event Revealer", eventResults1: [eventResult38a, eventResult38b, eventResult38c, eventResult38d])
        allHuntEvents.append(huntEvent38)
        
        let huntEvent39 = HuntEvent(eventNumber: "38", eventText: NSMutableAttributedString().appendWith("A heavy mist envelops the survivors, obscuring their lantern light. Roll 1d10. If the result is even, the survivors stumble in the right direction. If the result is odd, they get turned around; roll again on the hunt event table before moving on the hunt event board.\n\nIf the showdown begins in the next space on the hunt board, the monster ").appendWith(weight: .bold, "ambushes").appendWith(" the survivors."), eventTitle: "39 | Heavy Mist", eventDie: "N/A", eventDieRoller1: "N/A", eventResults1: [])
        allHuntEvents.append(huntEvent39)
        
        let huntEvent40 = HuntEvent(eventNumber: "39", eventText: NSMutableAttributedString().appendWith("The event revealer dreams of the upcoming hunt. They stand before the great beast, weapons ready, but the beast strikes them down.\n\nIf the event revealer has 3+ courage, or if any survivor is a savior, the event revealer is emboldened by the dream and gains +1 evasion token. Otherwise the dream is merely rattling. Suffer 1 brain event damage.\n\nIf any survivor has the ").appendWith(weight: .bold, "Twilight Sword").appendWith(", they dream of indiscriminate slaughter. Add the ").appendWith(weight: .bold, "Murder").appendWith(" settlement event to the timeline 1d5 years from now."), eventTitle: "40 | Dream", eventDie: "N/A", eventDieRoller1: "N/A", eventResults1: [])
        allHuntEvents.append(huntEvent40)
        
        let huntEvent41 = HuntEvent(eventNumber: "40", eventText: NSMutableAttributedString().appendWith("The event revealer dreams of the upcoming hunt. The great beast vanishes during their battle and secretly follows them back to the settlement. They helplessly watch as it devours all they know and love. The event revealer gains +1d10 insanity and -1 evasion token.\n\nIf the settlement has a savior, they appear in the dream and defend their home. The event revealer gains +1d5 survival.\n\nIf no survivor in the settlement or hunting party has a ").appendWith(weight: .bold, "Twilight Sword").appendWith(", the event revealer envisions a maniacal version of themsevles wielding a blade and gleefully slaughtering the beast. They awake to find a Twilight Sword at their side, humming gently against their body. Instinctively the survivor recognizes the weight of the weapon's curse and the promise of its power. The event revealer gains the Twilight Sword rare gear. They may also select ").appendWith(weight: .bold, "Twilight Sword").appendWith(" as their weapon proficiency type and gain +1 weapon proficiency with this weapon."), eventTitle: "41 | Nightmare", eventDie: "N/A", eventDieRoller1: "N/A", eventResults1: [])
        allHuntEvents.append(huntEvent41)
        
        let huntEvent42 = HuntEvent(eventNumber: "41", eventText: NSMutableAttributedString().appendWith("A creaky carriage approaches the survivors. Richly appointed in red and gold, the carriage is carved on every side with lurid faces. A massive, twitching eye adorns the front, while the door of the carriage is a waiting, open mouth.\n\nOut of a small window, a gnarled hand beckons. One survivor with 3+ courage may choose to enter the wagon. They remove one impairment or severe injury and gain 1 random disorder."), eventTitle: "42 | Surgeon", eventDie: "N/A", eventDieRoller1: "N/A", eventResults1: [])
        allHuntEvents.append(huntEvent42)
        
        let huntEvent43 = HuntEvent(eventNumber: "42", eventText: NSMutableAttributedString().appendWith("A carpet of skittering bugs points the survivors to a freshly-killed monster. The scavenging insects try to defend their dinner, but the survivors fight them off to claim the prize.\n\nEach survivor rolls 2d10 and adds their HuntXP. The highest-scoring survivor (roll off in case of ties) slays the most vermin and wins the putrid prize for themselves. They gain 1 random basic resource and 1 random vermin resource."), eventTitle: "43 | Fresh Kill", eventDie: "N/A", eventDieRoller1: "N/A", eventResults1: [])
        allHuntEvents.append(huntEvent43)
        
        let huntEvent44 = HuntEvent(eventNumber: "43", eventText: NSMutableAttributedString().appendWith("While investigating their quarry's tracks, the survivors realize they are hunting not one, but two monsters. The two sets of tracks soon separate, leaving the event revealer to pick which tracks to follow.\n\nIf they follow the larger tracks, continue hunting as normal. If they follow the smaller tracks, start the showdown immediately. At the start of the showdown, the monster suffers 5 wounds. If the survivors are victorious, they gain half the basic resources and half the monster resources (rounded up) from rewards in the aftermath."), eventTitle: "44 | Opportunists", eventDie: "N/A", eventDieRoller1: "N/A", eventResults1: [])
        allHuntEvents.append(huntEvent44)
        
        let eventResult45a = EventResult(eventDieResult: "1", eventResultDescription: NSMutableAttributedString().appendWith("The white stones are teeth and the survivors are in a giant mouth! Everyone must spend 1 survival to scamper out of the mouth. Anyone remaining inside is chewed to a pulp. Dead. Do not gain the benefits of ").appendWith(weight: .bold, "Cannibalize."))
        let eventResult45b = EventResult(eventDieResult: "2 - 5", eventResultDescription: NSMutableAttributedString().appendWith("The white stone is extremely hard. When the survivors finally break through, a horde of bugs scuttles forth from the holes. Gain 1 ").appendWith(weight: .bold, "Hissing Cockroach").appendWith(" vermin resource. The evacuation was time consuming; roll again on the hunt event table before moving on the hunt board."))
        let eventResult45c = EventResult(eventDieResult: "6+", eventResultDescription: NSMutableAttributedString().appendWith("The survivors find a crack and expand it. Within is a hidden cache! Gain 1 ").appendWith(weight: .bold, "Iron").appendWith(" strange resource and 1 ").appendWith(weight: .bold, "Hissing Cockroach").appendWith(" vermin resource. The excavation was time consuming; roll again on the hunt event table before moving on the hunt board."))
        let huntEvent45 = HuntEvent(eventNumber: "44", eventText: NSMutableAttributedString().appendWith("A valley of sharp, white stones opens before the survivors, looking just like a toothy maw. As the survivors push and climb through the jagged spires, they find that even the shallowest nick bleeds profusely. Each survivor suffers 1 event damage to the body. Unless a survivor has bandages to patch up their wounds, all survivors also gain 2 bleeding tokens!\n\nIf any survivor has a pickaxe, they may try to convince the other survivors to let them ").appendWith(weight: .bold, "investigate").appendWith(" a bit more. If they are convinced, roll 1d10."), eventTitle: "45 | Jagged Valley", eventDie: "1d10", eventDieRoller1: "Survivor carrying a pickaxe - Investigate", eventResults1: [eventResult45a, eventResult45b, eventResult45c])
        allHuntEvents.append(huntEvent45)
        
        let eventResult46a = EventResult(eventDieResult: "1 - 2", eventResultDescription: NSMutableAttributedString().appendWith("You lose your balance and fall into the river of blood! Instantly, a massive parasite crams its way down your throat, savaging your insides on the way down. Suffer the ").appendWith(weight: .bold, "broken rib").appendWith(" severe body injury. You hope that that's all the parasite does to you."))
        let eventResult46b = EventResult(eventDieResult: "3 - 5", eventResultDescription: NSMutableAttributedString().appendWith("Your quarry has defecated in the blood. Sufer 1 event damage to a random hit location from sifting through the fecal blood water too long."))
        let eventResult46c = EventResult(eventDieResult: "6 - 8", eventResultDescription: NSMutableAttributedString().appendWith("You realize that the blood river is filled with the bloated corpses of unrecognizable monsters. You feel compelled to fish some out! Gain 1 random basic resource. If you are wearing ").appendWith(weight: .bold, "heavy").appendWith(" gear, you fall in and swallow blood and soft, boated monster bits. Reduce your surival to 1."))
        let eventResult46d = EventResult(eventDieResult: "9+", eventResultDescription: NSMutableAttributedString().appendWith("You successfully find the monster's trail."))
        let huntEvent46 = HuntEvent(eventNumber: "45", eventText: NSMutableAttributedString().appendWith("The survivors come to the edge of a river of blood. ").appendWith(weight: .bold, "Non-insane").appendWith(" survivors suffer 1 brain event damage at the sight of it. The survivors must investigate in order to pick up their quarry's trail. Each survivor rolls 1d10.\n\nIf no survivor successfully finds the monster's trail, roll again on the hunt event table before moving on the hunt board."), eventTitle: "46 | River", eventDie: "1d10", eventDieRoller1: "Each survivor - Investigate", eventResults1: [eventResult46a, eventResult46b, eventResult46c, eventResult46d])
        allHuntEvents.append(huntEvent46)
        
        let eventResult47a = EventResult(eventDieResult: "1 - 5", eventResultDescription: NSMutableAttributedString().appendWith("The addictive fruit savages your insides. Lose 1 survival and roll again on this table. If you had no survival, suffer 2 event damage to a random hit location."))
        let eventResult47b = EventResult(eventDieResult: "6+", eventResultDescription: NSMutableAttributedString().appendWith("You belch loudly in satisfaction and walk away."))
        let huntEvent47 = HuntEvent(eventNumber: "46", eventText: NSMutableAttributedString().appendWith("A small copse of trees rises over an otherwise lifeless plain. Enticing red fruit hangs from the branches. Each survivor must spend 1 survival to resist the temptation to ").appendWith(weight: .bold, "consume").appendWith(" the fruit. ").appendWith(weight: .bold, "Insane").appendWith(" survivors and survivors with the ").appendWith(weight: .bold, "Binge Eating").appendWith(" disorder must ").appendWith(weight: .bold, "consume").appendWith(".\n\nIf any survivor has a sickle, they carve a line across the tree, drawing blood! The fruit instantly sours. End this event.\n\nAll survivors who consume the fuit roll 1d10."), eventTitle: "47 | Banquet Trees", eventDie: "1d10", eventDieRoller1: "Any survivor - Consume", eventResults1: [eventResult47a, eventResult47b])
        allHuntEvents.append(huntEvent47)
        
        let eventResult48a = EventResult(eventDieResult: "1", eventResultDescription: NSMutableAttributedString().appendWith("The Gambler reaches out and scoops up your dice. As they vanish within a fold of his cloak, you feel all traces of air leave your lungs and you are unable to draw another breath. Dead."))
        let eventResult48b = EventResult(eventDieResult: "2 -9", eventResultDescription: NSMutableAttributedString().appendWith("You do not lose, nor do you win. Play again if you wish. If you do, roll again on this table."))
        let eventResult48c = EventResult(eventDieResult: "10+", eventResultDescription: NSMutableAttributedString().appendWith("You win. Gain +1 permanent luck."))
        let huntEvent48 = HuntEvent(eventNumber: "47", eventText: NSMutableAttributedString().appendWith("The survivors are awakened by a traveler hidden in a deep cloak. The traveler pulls back its hood and reveals a deformed face with two chins curving away from each other, each with its own grinning mouth.\n\nIn a dreamlike state, the survivors all understand this entity is known as The Gambler and if they speak they will die. Until this event is completed, only the event revealer may speak. If any other player speaks, their survivor turns cold. Dead.\n\nThe survivors must play The Gambler's game or be trapped with him forever. Each survivor rolls 1d10."), eventTitle: "48 | Death Wager", eventDie: "1d10", eventDieRoller1: "Each survivor", eventResults1: [eventResult48a, eventResult48b, eventResult48c])
        allHuntEvents.append(huntEvent48)
        
        let huntEvent49 = HuntEvent(eventNumber: "48", eventText: NSMutableAttributedString().appendWith("The landscape is dotted with large, swelling mounds oozing pus. The smallest jostle threatens to explode them. The survivors may ").appendWith(weight: .bold, "carefully tread").appendWith(" through the mounds or ").appendWith(weight: .bold, "rush through").appendWith(".\n\n").appendWith(weight: .bold, "Carefully tread").appendWith(": You make it through without incident, but your progress is slowed. Roll again on the hunt event table before moving on the hunt board.\n\n").appendWith(weight: .bold, "Rush through").appendWith(": Each survivor rolls 1d10 and adds their evasion to the result. On a 7 or less, they detonate one of the pus mounds! They suffer to event damage to a random hit location and become ").appendWith(weight: .bold, "stinky").appendWith(" for the rest of this lantern year."), eventTitle: "49 | Pus Fields", eventDie: "N/A", eventDieRoller1: "N/A", eventResults1: [])
        allHuntEvents.append(huntEvent49)
        
        let eventResult50a = EventResult(eventDieResult: "1", eventResultDescription: NSMutableAttributedString().appendWith("The survivors open the cage but all they find inside is a skeleton. All survivors suffer 2 brain event damage"))
        let eventResult50b = EventResult(eventDieResult: "2 - 7", eventResultDescription: NSMutableAttributedString().appendWith("The prisoner is thankful and follows the survivors until they rest. When they wake, each survivor loses 1 random resource (if they had any)."))
        let eventResult50c = EventResult(eventDieResult: "8+", eventResultDescription: NSMutableAttributedString().appendWith("The prisoner is grateful and follows the survivors home after the showdown. The settlement gains +1 population."))
        let huntEvent50 = HuntEvent(eventNumber: "49", eventText: NSMutableAttributedString().appendWith("A crude iron cage swings from the branches of a massive tree. As the survivors approach, a man calls out to them from the cage, pleading to be freed. The survivors may pass him by and suffer 1 brain event damage as the prisoner weeps and pleads. If the survivors choose to free him, the event revealer rolls 1d10."), eventTitle: "50 - Gibbet", eventDie: "1d10", eventDieRoller1: "Event revealer", eventResults1: [eventResult50a, eventResult50b, eventResult50c])
        allHuntEvents.append(huntEvent50)
        
        let huntEvent51 = HuntEvent(eventNumber: "50", eventText: NSMutableAttributedString().appendWith("The survivors encounter a group of fleeing settlers. If the settlement has ").appendWith(weight: .bold, "Symposium").appendWith(" and ").appendWith(weight: .bold, "Language").appendWith(", the survivors manage to crudely communicate. The survivors may offer a resource or gear to help the distressed refugees.\n\nIf they do, archive the offering. The refugees frantically share their mournful tale. While much is lost in translation, they relate the savage invasion of a monster that destroyed their home. The tale prepares the survivors for what lies ahead. At the start of the showdown, reveal the top 5 AI cards of the AI deck and put them back in any order. If any survivor has the ").appendWith(weight: .bold, "Leader").appendWith(" fighting art, one of the settlers is drawn to their charisma. Gain +1 population."), eventTitle: "51 | Refugees", eventDie: "N/A", eventDieRoller1: "N/A", eventResults1: [])
        allHuntEvents.append(huntEvent51)
        
        let eventResult52a = EventResult(eventDieResult: "1 -2", eventResultDescription: NSMutableAttributedString().appendWith("You dive into a nearby marsh to flush out the disgusting insects. It works, but now you're constantly distracted by the tiny bug corpses you occasionally hack up. Gain -1 evasion token."))
        let eventResult52b = EventResult(eventDieResult: "3 - 7", eventResultDescription: NSMutableAttributedString().appendWith("The buzzing immediately stops and the flies depart. Their rejection makes you feel strangely despondent. Gain +1 insanity."))
        let eventResult52c = EventResult(eventDieResult: "8+", eventResultDescription: NSMutableAttributedString().appendWith("Their eggs gestate incredibly quickly and madflies explode forth from your mouth! The experience is gruesome, but makes you feel so alive! Suffer the ").appendWith(weight: .bold, "frenzy").appendWith(" brain trauma.\n\nIf you have the ").appendWith(weight: .bold, "Rageholic").appendWith(" or ").appendWith(weight: .bold, "Berserker").appendWith(" fighting art, giving birth to disgustin new life kindles your rage. Suffer the ").appendWith(weight: .bold, "frenzy").appendWith(" brain trauma again."))
        let huntEvent52 = HuntEvent(eventNumber: "51", eventText: NSMutableAttributedString().appendWith("Tiny, persistent insects swarm the survivors, flying into their ears and nostrils. The bugs buzz maddeningly in their heads, growing louder as they nest.\n\nEach survivor rolls 1d10."), eventTitle: "52 | Madflies", eventDie: "1d10", eventDieRoller1: "Each survivor", eventResults1: [eventResult52a, eventResult52b, eventResult52c])
        allHuntEvents.append(huntEvent52)
        
        let eventResult53a = EventResult(eventDieResult: "1 - 3", eventResultDescription: NSMutableAttributedString().appendWith("The salesman silently points at you. You instinctively hand him his asking price in exchange for the mask. Archive 1 gear of your choice from your gear grid and lose all survival."))
        let eventResult53b = EventResult(eventDieResult: "4 = 7", eventResultDescription: NSMutableAttributedString().appendWith("The salesman slowly gestures for an offering. Archive 1 gear of your choice from your gear grid."))
        let eventResult53c = EventResult(eventDieResult: "8+", eventResultDescription: NSMutableAttributedString().appendWith("As he imparts the mask to you, the salesman's lips form the sounds of your name. It is gone. Give your survivor a new name (it must be different) and +1 survival for naming your survivor."))
        let huntEvent53 = HuntEvent(eventNumber: "52", eventText: NSMutableAttributedString().appendWith("The survivors meet a traveling Mask Salesman on the road. He insists that he has special wares to offer.\n\nShuffle one copy of each mask gear from the Mask Maker settlement location and draw one at random. The salesman is offering this mask. The event revealer rolls 1d10 to determine the price, then gains the mask."), eventTitle: "53 | Mask Salesman", eventDie: "1d10", eventDieRoller1: "Event revealer", eventResults1: [eventResult53a, eventResult53b, eventResult53c])
        allHuntEvents.append(huntEvent53)
        
        let huntEvent54 = HuntEvent(eventNumber: "53", eventText: NSMutableAttributedString().appendWith("Mighty winds tear across the landscape, collecting chips of stones and skeletal remains. The survivors huddle together on the outskirts of the storm. They may either ").appendWith(weight: .bold, "brave the storm").appendWith(" or ").appendWith(weight: .bold, "wait it out").appendWith(".\n\n").appendWith(weight: .bold, "Brave the storm").appendWith(": all survivors gain +1 courage and suffer 1 event damage to 3 random hit locations. Archive all ").appendWith(weight: .bold, "fragile").appendWith(" gear.\n\n").appendWith(weight: .bold, "Wait it out").appendWith(": roll twice on the hunt even table before moving on the hunt board."), eventTitle: "54 | Bone storm", eventDie: "N/A", eventDieRoller1: "N/A", eventResults1: [])
        allHuntEvents.append(huntEvent54)
        
        let eventResult55a = EventResult(eventDieResult: "1 -2", eventResultDescription: NSMutableAttributedString().appendWith("You're violently swept along, drowning in mud. Suffer 2 event damage to a random hit location and archive all ").appendWith(weight: .bold, "fragile").appendWith(" and ").appendWith(weight: .bold, "soluble").appendWith(" gear in your gear grid. Roll again on the table."))
        let eventResult55b = EventResult(eventDieResult: "3 - 7", eventResultDescription: NSMutableAttributedString().appendWith("You manage to scramble free, but not before taking a serious beating. Suffer 2 event damage to your body and archive all ").appendWith(weight: .bold, "fragile").appendWith(" and ").appendWith(weight: .bold, "soluble").appendWith(" gear in your gear grid."))
        let eventResult55c = EventResult(eventDieResult: "8 - 9", eventResultDescription: NSMutableAttributedString().appendWith("You reach higher ground. You're caked in mud but otherwise unscathed."))
        let eventResult55d = EventResult(eventDieResult: "10+", eventResultDescription: NSMutableAttributedString().appendWith("You remember being pulled under, the sensation of mud forcing itself down your throat, then nothing else. After the mudslide passes, the other survivors find you unharmed. Gain +1 insanity."))
        let huntEvent55 = HuntEvent(eventNumber: "54", eventText: NSMutableAttributedString().appendWith("A flash mudslide sweeps the survivors away.\n\nEach survivor rolls 1d10. If any survivor has a whip, they catch it around a pillar-shaped bone and swing to safety; they do not roll."), eventTitle: "55 | Mudslide", eventDie: "1d10", eventDieRoller1: "Each survivor", eventResults1: [eventResult55a, eventResult55b, eventResult55c, eventResult55d])
        allHuntEvents.append(huntEvent55)
        
        let huntEvent56 = HuntEvent(eventNumber: "55", eventText: NSMutableAttributedString().appendWith("The survivors find a decomposed monster corpse. It's too rotten to yield any resources.\n\nIf any survivor has 3+ understanding, the survivors cover themselves in the dead monster's spilled blood. The stench will help them sneak up on their quarry. When the showdown begins, the survivors ").appendWith(weight: .bold, "ambush").appendWith(" the monster. If any survivor has the ").appendWith(weight: .bold, "Squeamish").appendWith(" disorder, they refuse to soil themselves. Do not ").appendWith(weight: .bold, "ambush").appendWith(" the monster.\n\nIf no survivor has 3+ understanding, the starving survivors feast on the rotting corpse, immediately losing control of their twisting guts. Each survivor loses 1 survival and cannot ").appendWith(weight: .bold, "consume").appendWith(" for the rest of this lantern year."), eventTitle: "56 | Dead Monster", eventDie: "N/A", eventDieRoller1: "N/A", eventResults1: [])
        allHuntEvents.append(huntEvent56)
        
        let huntEvent57 = HuntEvent(eventNumber: "56", eventText: NSMutableAttributedString().appendWith("The rhythmic wail of a Gorm's laughter reaches the survivors, filling them with fear. The cackling follows the survivors, tormenting them until they reach their quarry. Place a token on every hunt board space between the survivors and their quarry. When the survivors move into a space with a token, remove it and all ").appendWith(weight: .bold, "non-deaf").appendWith(" survivors suffer 1 brain event damage."), eventTitle: "57 | Gorm's Laughter", eventDie: "N/A", eventDieRoller1: "N/A", eventResults1: [])
        allHuntEvents.append(huntEvent57)
        
        let eventResult58a = EventResult(eventDieResult: "1 - 5", eventResultDescription: NSMutableAttributedString().appendWith("The monster catches your scent. It moves one space closer. If this movement starts the showdown, the monster ").appendWith(weight: .bold, "ambushes").appendWith(" the survivors."))
        let eventResult58b = EventResult(eventDieResult: "6+", eventResultDescription: NSMutableAttributedString().appendWith("The survivors smell their quarry's foul odor and surge forward. The survivors may skip the next hunt space. If this movement starts the showdown, the survivors ").appendWith(weight: .bold, "ambush").appendWith(" the monster."))
        let huntEvent58 = HuntEvent(eventNumber: "57", eventText: NSMutableAttributedString().appendWith("A strong wind blows, bringing with it the scents of distant places and things. The event revealer rolls 1d10."), eventTitle: "58 | Scent on the Wind", eventDie: "1d10", eventDieRoller1: "Event revealer", eventResults1: [eventResult58a, eventResult58b])
        allHuntEvents.append(huntEvent58)
        
        let eventResult59a = EventResult(eventDieResult: "1 - 2", eventResultDescription: NSMutableAttributedString().appendWith("The monster springs out of the dark, taking advantage of the distracted survivors. The monster ").appendWith(weight: .bold, "ambushes").appendWith(" the survivors. During the showdown setup, place the event revealer directly in front of the monster."))
        let eventResult59b = EventResult(eventDieResult: "3 - 7", eventResultDescription: NSMutableAttributedString().appendWith("The remains are human. The distraught and enraged survivors each suffer 1 brain event damage. If the settlement has ").appendWith(weight: .bold, "Graves").appendWith(", they bury the dead and each survivor gains +1 survival. If the settlement has ").appendWith(weight: .bold, "Cannibalize").appendWith(", gain 1 random basic resource."))
        let eventResult59c = EventResult(eventDieResult: "8+", eventResultDescription: NSMutableAttributedString().appendWith("The quarry has left the remains of another monster in its wake. Gain 1 random basic resource."))
        let huntEvent59 = HuntEvent(eventNumber: "58", eventText: NSMutableAttributedString().appendWith("The survivors come upon the remains of a terrible battle between their quarry and some unknown foe. The event revealer may choos to ").appendWith(weight: .bold, "investigate").appendWith(". If they do, gain +1 courage and roll 1d10. Otherwise, roll again on the hunt even table before moving on the hunt board."), eventTitle: "59 | Signs of Battle", eventDie: "1d10", eventDieRoller1: "Event revealer - Investigate", eventResults1: [eventResult59a, eventResult59b, eventResult59c])
        allHuntEvents.append(huntEvent59)
    }
}

